### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by anggaand123** [ionic-team/ionic-native-google-maps#57]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.4.2 "cordova-plugin-filepath"
cordova-plugin-googlemaps 2.3.11-beta-20180808-1939 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
```

**Stacktrace:**
```
FAILURE:
Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'                                                                                                                                                 .
> A problem occurred starting process 'command 'C:\Users\Angga Andrean\AppData\L                                                                                                                                                 ocal\Android\sdk\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windo                                                                                                                                                 ws-x86_64\bin\mips64el-linux-android-strip''

* Try:
Run with
--stacktrace option to get the stack trace. Run with --info or --debug option to                                                                                                                                                  get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED
45 actionable tasks: 11 executed, 34 up-to-date
 in 42s
(node:21180) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with e                                                                                                                                                 xit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'                                                                                                                                                 .
> A problem occurred starting process 'command 'C:\Users\Angga Andrean\AppData\L                                                                                                                                                 ocal\Android\sdk\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windo                                                                                                                                                 ws-x86_64\bin\mips64el-linux-android-strip''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                                                  option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
    at ChildProcess.whenDone (E:\Project\ionic\skalasound\platforms\android\cord                                                                                                                                                 ova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:21180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                                                                                                  error originated either by throwing inside of an async function without a catch                                                                                                                                                  block, or by rejecting a promise which was not handled with .catch(). (rejectio                                                                                                                                                 n id: 1)
(node:21180) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr                                                                                                                                                 ecated. In the future, promise rejections that are not handled will terminate th                                                                                                                                                 e Node.js process with a non-zero exit code.
```

i try with your suggestion on here https://github.com/ionic-team/ionic-native-google-maps/issues/53

**Comment by wf9a5m75** [comment]
That's your gradle environment problem.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/mips64el-linux-android-strip/README.md

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by anggaand123** [comment]
i have tried to remove NDK from SDK Manager .
and then i compile again, it work
