### ISSUE TITLE
Ionic 3: markerCluster icons not loading: AsyncLoadImage Connect refused

### ISSUE THREAD

**Issue by jrmistry** [ionic-team/ionic-native-google-maps#70]
Hi Thank You for supporting this pulgin.

I am having a weird issue with my Ionic 3 Android project that uses this GoogleMaps pulgin, specifically that my markerCluster icons sometimes do not load. I have the icon images stored right on the device assets folder, and I believe I am calling the markerClusterOptions correctly, but there is almost a 50-50 % chance that the icons that I specify will load, and the other 50% of the time the default red markers are loading in their place.

- [ ] question
- [x ] **any problem or bug report**
- [ ] feature request

OS I am developing for is Android, however I will also try to build it for iOS in the future.
- [x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**

cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sms-plugin 0.1.13 "Cordova SMS Plugin"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
I currently have "@ionic-native/google-maps": "^4.12.0"

**Current behavior:**
The yellow marker icons are individual bus stops which is fine. But red marker icons are being used in place for the markerCluster images that I want.
![image](https://user-images.githubusercontent.com/8127024/44961424-0f27b280-aedf-11e8-979d-253de8f22549.png)

**Expected behavior:**
The app needs to use the marker cluster Icons that I specify, and are stored inside the assets folder. There is almost a 50% chance that they will load correctly.
![image](https://user-images.githubusercontent.com/8127024/44961437-3a120680-aedf-11e8-8f86-f6a5f732b1a9.png)
![image](https://user-images.githubusercontent.com/8127024/44961442-44cc9b80-aedf-11e8-89d0-bf3e257cb272.png)

**Related code, data or error log (please format your code or data):**
https://github.com/jrmistry/BUS_TXT
I believe my entire project code base is on the Github Repo. If you need me to provide any more information then let me know.

**More Context:**
The point of the app is to show bus stops in the town of Waterloo, Canada. Since the town has 2500+ bus stops, all located densely together, I needed to cluster them. The icon for each bus stop is the yellow marker icon.

![image](https://user-images.githubusercontent.com/8127024/44961505-25823e00-aee0-11e8-885b-51bd3c821234.png)
I have tried to run the app on both an emulator, and on my mobile phone Samsung Galaxy Note 5 (Android Version 7.0), and both times faced the issue of the markerCluster icons not showing up sometimes. I find this issue most bizarre because of the unpredictability of the issue, and all of my efforts have failed.

**MOST IMPORTANTLY**
When I am running the app on my emulator, and only the times when the markerCluster icons do not load, I get this error on the console for EACH of the markerCluster icons that did not load in the map view at that time. As I zoom out and the number of clusters decrease, more of these errors get logged for each missing markerCluster icon.

The weirder thing is that when I open the app and the markerCluster icons do load, they will load correctly for the rest of the time that I have the app open, regardless of how many times I interact with the map. When I open the map and the markerCluster icon have not loaded correctly, for the rest of the time I used the app the markerCluster icons will always load as the default red icons, and that is for all the cluster sizes.

09-02 22:00:45.858 12306-12629/io.bus_txt E/AsyncLoadImage: can not connect to http://localhost:8080/assets/markercluster/m1.png
    java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:605)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:196)
        at com.android.okhttp.Connection.connect(Connection.java:172)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:281)
        at plugin.google.maps.AsyncLoadImage.doInBackground(AsyncLoadImage.java:27)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by jrmistry** [comment]
Hi that did fix the issue. Thank you.

If you don't mind could I know why that branch had the fix and what the real issue was?

**Comment by wf9a5m75** [comment]
Sorry, but I can't understand your English.

**Comment by jrmistry** [comment]
I wanted to know what the real problem was and why the multiple_maps branch fixed it?

**Comment by wf9a5m75** [comment]
It's a bug of ionic 3 server.
As you can see in the error log, the maps plugin make a http request to `http://localhost:8080/assets/markercluster/m1.png`.
But the ionic3 server refused. That's the problem.

In the multiple_maps branch code, the maps plugin loads the file from `file://` if url stars with `http://localhost`.
That's all.
