### ISSUE TITLE
Error while build android

### ISSUE THREAD

**Issue by bhumin3i** [ionic-team/ionic-native-google-maps#79]
Error after adding google map plugin :(
android: 7.1.0

**ERROR LOG**
```
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/rac/Desktop/git/cccc/platforms/android/app/build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/rac/Desktop/git/cccc/platforms/android/app/cordova-android-support-gradle-release/properties.gradle
ANDROID_HOME=/Users/rac/Library/Android/sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_2cmox5frm1w69pcqug7lw4u1l.run(/Users/rac/Desktop/git/cccc/platforms/android/app/build.gradle:153)

FAILURE: Build failed with an exception.

* Where:
Script '/Users/rac/Desktop/git/rti-campus-app-frontend/platforms/android/cordova-support-google-services/campus-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > All firebase libraries must be either above or below 14.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:25000) UnhandledPromiseRejectionWarning: Error: /Users/rac/Desktop/git/rti-campus-app-frontend/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/Users/rac/Desktop/git/cccc/platforms/android/cordova-support-google-services/campus-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > All firebase libraries must be either above or below 14.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (/Users/rac/Desktop/git/cccc/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:25000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**project.profile**

```
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-android-support-gradle-release/campus-cordova-android-support-gradle-release.gradle
cordova.gradle.include.2=cordova-plugin-background-fetch/campus-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/campus-build.gradle
cordova.gradle.include.4=cordova-plugin-badge/campus-badge.gradle
cordova.gradle.include.5=cordova-plugin-googlemaps/campus-tbxml-android.gradle
cordova.system.library.3=com.google.android.gms:play-services-maps:15.0.1
cordova.system.library.4=com.google.android.gms:play-services-location:15.0.1
cordova.system.library.5=com.android.support:support-core-utils:27.+
cordova.system.library.6=com.android.support:support-v4:26.+
cordova.gradle.include.6=cordova-plugin-local-notification/campus-localnotification.gradle
cordova.gradle.include.7=cordova-plugin-ms-adal/campus-adal.gradle
cordova.gradle.include.8=cordova-support-google-services/campus-build.gradle
cordova.gradle.include.9=phonegap-plugin-barcodescanner/campus-barcodescanner.gradle
cordova.system.library.7=com.android.support:support-v4:27.+
cordova.gradle.include.10=phonegap-plugin-multidex/campus-multidex.gradle
cordova.system.library.8=com.android.support:support-v13:27.+
cordova.system.library.9=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.10=com.google.firebase:firebase-messaging:11.8.0
cordova.system.library.11=io.sentry:sentry-android:1+
```

![screen shot 2018-09-18 at 8 02 05 pm](https://user-images.githubusercontent.com/25737987/45694899-ddb91300-bb7d-11e8-87ab-b286ecbc2984.png)

![screen shot 2018-09-18 at 8 02 28 pm](https://user-images.githubusercontent.com/25737987/45694887-d85bc880-bb7d-11e8-8f15-c171470c1b9b.png)

**Comment by wf9a5m75** [comment]
Not this plugin's problem.

>* Where:
>Script '/Users/rac/Desktop/git/rti-campus-app-frontend/platforms/android/cordova-support-google-services/campus-build.gradle' line: 16
>
>* What went wrong:
>A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
>   > All firebase libraries must be either above or below 14.0.0

**Comment by wf9a5m75** [comment]
ping

**Comment by YaroslavG** [comment]
Hello @bhumin3i , I have the same problem, what solution to solve this you accepted?
